image: mohanlu/cv_detection:latest 


before_script:
  - apt-get update -y && apt-get install fd-find -y
  - ln -s $(which fdfind) /usr/local/bin/fd || true
  - which fd || which fdd || which fdfind
  - apt-get install build-essential -y
  - apt-get install python3-pip -y # Ensure pip is available for installing pre-commit
  - pip3 install pre-commit
  - git config --global user.email "you@example.com"
  - git config --global user.name "CI Auto Formatter"
  # - ls -l /opt/ros/iron/
  # - source /opt/ros/iron/setup.bash
  # - echo "ROS 2 environment sourced"
  - git fetch
  - git remote add gitlab_origin https://oauth2:glpat-7GrwyrPa-7CqntJpe_8R@gitlab.com/nyu-robomaster/cv_detection.git
  - git checkout $CI_COMMIT_REF_NAME
  # - chmod +x /builds/nyu-robomaster/controls_ros/scripts/run-clang-tidy.sh


lint:
  stage: test
  script:
    - cd /builds/nyu-robomaster/CV_Detection/ # Change directory to where your code is
    - pre-commit run --all-files || true # Run pre-commit and ignore failure
    - |
      if [ -n "$(git status --porcelain)" ]; then # Check if there are any changes
        git add .
        git commit -m "Apply clang-format fixes"
        git push 
      fi

# pre_commit:
#   stage: pre_commit
#   script:
#     - pre-commit clean
#     - pre-commit run --all-files 
