repos:
  # Black for formatting Python code consistently.
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  # Pyupgrade for upgrading Python syntax to newer versions.
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: [--py39-plus]

  # # MyPy for static type checking of Python code.
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.8.0
  #   hooks:
  #     - id: mypy
  #       additional_dependencies: [types-all]

  # # Codespell for identifying common misspellings in text files.
  # - repo: https://github.com/codespell-project/codespell
  #   rev: v2.1.0
  #   hooks:
  #     - id: codespell
  #       args: ['--ignore-words-list=nd,amin']

  # Commitlint for enforcing conventional commit messages.
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v5.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]

  # Collection of utility hooks for general code quality checks.
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # - id: requirements-txt-fixer
      - id: check-yaml
      - id: debug-statements
      - id: check-json
      - id: check-merge-conflict

  # Custom hook for checking non-real mock methods in Python code.
  - repo: local
    hooks:
      - id: python-check-mock-methods
        name: Check for not-real mock methods
        entry: '\bmock\.assert_\w+\(\)'
        language: pygrep
        types: [python]
